### PR TITLE
Improve Patient record page

### LINKED ISSUE #137: Improve patient record immunization information
There are still some hardcoded pieces in the view and also some edge case handling has to be done

### LINKED ISSUE #139: Fix sidebar width
The sidebars for the disease and vaccine settings as well as the disease record in the MD dashboard have inconsistent width. Make them consistent with the main sidebar of the patient overview.

### PR DESCRIPTION
**Pull request by FuchsDominik**
- Improve information page with valid data
- Remove configuration tab

### CODE REVIEW

**Review by ValiHar — COMMENTED** [review]
Why did you remove the tab and the immunization configuration component? Where is that going to happen? :)

**Comment by ValiHar** [comment]
The corners of the display area of the disease record are not rounded yet and there should be a margin on the left side of the sidebar where you select the disease you want to get informations about.

**Comment by ValiHar** [comment]
The content area of the disease record should be full width and the labels inside are currently overflowing with text.

**Review by ValiHar — CHANGES_REQUESTED** [review]
Lets iterate over this once more to make it pretty :)

**Comment by FuchsDominik** [comment]
As discussed, no configuration page, also see comment in issue #135. I did leave out the margin on the left side on purpose, thought it would look kind if good. Same for the not-full-width of the information container (We don't need all the space as there is not too much to display IMO). I can, of course, change it the way you suggested.

**Review by ValiHar — APPROVED** [review]

**Pull request merged**
